// SPDX-FileCopyrightText: 2025-2026 Volodymyr Papush (21CNCStudio)
// SPDX-License-Identifier: GPL-3.0-or-later
// GPL-3.0-or-later: https://www.gnu.org/licenses/gpl-3.0.html
// Want to use this code in a commercial product while keeping modifications proprietary?
// Purchase a Commercial License: see COMMERCIAL_LICENSE_SUMMARY.md

#include "ui/UiStrings.h"

#include <stddef.h>

namespace UiStrings {

namespace {

constexpr const char *kStringsEn[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initializing",
    "Fresh Air - All Good",
    "Excellent",
    "Good",
    "Moderate",
    "Poor",
    "OFF",
    "ON",
    "OK",
    "ERR",
    "SYNC",
    "Connected",
    "AP Mode",
    "Error",
    "Connecting",
    "Disabled",
    "No WiFi",
    "Connected",
    "Error",
    "Retrying (10m)",
    "Retrying (1h)",
    "Connecting...",
    "ON / OFF",
    "Every 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Very High! Ventilate now",
    "CO2 High - Ventilate soon",
    "CO2 Rising - Consider ventilation",
    "PM2.5 Very High! Purify - stop smoke",
    "PM2.5 High - Purify - check source",
    "PM2.5 Elevated - Consider purifier",
    "PM10 Very High! Purify - check source",
    "PM10 High - Purify - reduce dust",
    "PM10 Elevated - Purify - reduce dust",
    "HCHO Very High! Ventilate - remove source",
    "HCHO High - Ventilate - remove source",
    "HCHO Detected - Check sources",
    "VOC Very High! Find source - vent",
    "VOC High - Increase ventilation",
    "NOx Very High! Stop source - ventilate",
    "NOx High - Use hood - check source",
    "NOx Elevated - Check stove/outside",
    "Temp Too Cold! Heat now",
    "Temp Cold - Heat the room",
    "Temp Slightly Cool - Add heat",
    "Temp Too Hot! Cool now",
    "Temp Warm - Ventilate / cool",
    "Temp Slightly Warm - Increase airflow",
    "DP Very Low! Humidify",
    "DP Low - Air may feel dry",
    "DP Muggy! Dehumidify now",
    "DP Very High - Vent/dehumidify",
    "DP High - Air may feel muggy",
    "Humidity Extremely Low! Humidify",
    "Humidity Very Low - Use humidifier",
    "Humidity Low - Consider humidifier",
    "Humidity Extremely High! Dehumidify",
    "Humidity Very High - Dehumidify",
    "Humidity High - Increase airflow",
    "SETTINGS",
    "SAVE & BACK",
    "TEMP OFFSET",
    "HUMID OFFSET",
    "NIGHT MODE",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "TIME / DATE",
    "THEME COLOR",
    "MQTT",
    "AUTO NIGHT",
    "RESTART",
    "FACTORY\nRESET",
    "CO2\nCALLIBRATION",
    "ABOUT",
    "DOT\nINDICATORS",
    "ALERT\nBLINK",
    "VOC\nRELEARN",
    "BACKLIGHT",
    "WI-FI SETTINGS",
    "Wi-Fi status:",
    "To configure Wi-Fi:\n- Press ON / OFF button\n- Connect your phone or PC to network \"ProjectAura-Setup\".\n- Open http://192.168.4.1 in browser or scan QR code.\n- Select your home Wi-Fi network and enter the password.\n",
    "SSID:",
    "IP:",
    "FORGET\nWI-FI",
    "RECONNECT",
    "START AP",
    "MQTT SETTINGS",
    "MQTT status:",
    "To configure MQTT:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/mqtt in browser or scan QR code.",
    "Device IP:",
    "Broker IP:",
    "Topic:",
    "RECONNECT",
    "DATE & TIME",
    "TIME ZONE",
    "AUTO SYNC (NTP)",
    "SET TIME",
    "Hours:",
    "Minutes:",
    "SET DATE",
    "Day:",
    "Month:",
    "Year:",
    "TIME",
    "APPLY NOW",
    "PCF8523:",
    "WIFI:",
    "NTP:",
    "STATUS: ",
    "TEMPERATURE",
    "HUMIDITY",
    "PRESSURE",
    "WARMUP",
    "RESET VOC",
    "RESTART",
    "RESET",
    "CANCEL",
    "Reset VOC Calibration?",
    "VOC/NOx learning will restart.\nReadings may be unstable for a few hours.",
    "Restart Device?",
    "The device will reboot.\nReadings will pause briefly.",
    "Factory Reset?",
    "This clears Wi-Fi, offsets, themes,\nschedules and VOC state.\nThis cannot be undone.",
    "THEME:",
    "CUSTOM",
    "PRESETS",
    "EXAMPLE:",
    "To configure custom theme:\n- Connect Project Aura to WI-FI first\n- Open http://aura.local/theme in browser \nor scan QR code.\n- Save by pressing Back",
    "AUTO NIGHT MODE",
    "This feature activates \"Night Mode\" colors based on a schedule.\n- Set Start and End times below.\n- Toggle the switch to ON.\n- Manual Night Mode is disabled when Auto Night is ON.",
    "START TIME",
    "END TIME",
    "SCREEN BACKLIGHT",
    "Device monitors air quality while screen is off.\nSensors remain active. Touch to wake.",
    "SCHEDULED SLEEP",
    "POWER SAVING",
    "SLEEP AT",
    "WAKE AT",
    "ALWAYS ON",
    "30 SEC",
    "1 MIN",
    "5 MIN",
    "CO2 Calibration (Fresh Air)",
    "CALIBRATE CO2",
    "- ASC (Automatic Self-Calibration): ON by default.\n- Best when CO2 drops close to outdoor levels at least weekly\n(good ventilation / room unoccupied).\n- ASC adjusts slowly over days (not instantly).\n- With ASC ON, manual calibration is usually \nnot needed.",
    "- Power the device from a power bank.\n- Take it outdoors to clean fresh air.\n- Keep it away from people (breath), windows, cars, smoke, vents.\n- Let it run for 10 minutes (minimum 5).\n- Press Calibrate CO2 and keep the device still.\n- Manual calibration is for troubleshooting only.\n- Do not calibrate more than once every 6 months.\n- Calibration uses a 420 ppm reference.\n- Wrong conditions can make readings worse.",
    "TAP TO CONTINUE",
    "BOOT DIAGNOSTICS",
    "System",
    "Sensors",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Storage:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "PCF8523:",
    "Errors detected",
    "OK (config)",
    "OK (defaults)",
    "RECOVERED",
    "DETECTED",
    "FAIL",
    "STARTING",
    "NOT FOUND",
    "LOST"
};

constexpr const char *kStringsDe[] = {
    "---",
    "--",
    "0%",
    "--:--",
    "--.--.----",
    "C",
    "F",
    "ppb",
    "Index",
    "HCHO",
    "AQI",
    "Initialisiere...",
    "Frische Luft - Alles gut",
    "Ausgezeichnet",
    "Gut",
    "Mittel",
    "Schlecht",
    "AUS",
    "AN",
    "OK",
    "ERR",
    "SYNC",
    "Verbunden",
    "AP Modus",
    "Fehler",
    "Verbinde...",
    "Deaktiviert",
    "Kein WLAN",
    "Verbunden",
    "Fehler",
    "Wiederholen (10m)",
    "Wiederholen (1h)",
    "Verbinde...",
    "AN / AUS",
    "Alle 6h",
    "http://192.168.4.1",
    "http://aura.local/mqtt",
    "http://aura.local/theme",
    "CO2 Sehr hoch! Jetzt lüften",
    "CO2 Hoch - Bald lüften",
    "CO2 Steigt - Lüften erwägen",
    "PM2.5 Sehr hoch! Reinigen - Rauch stoppen",
    "PM2.5 Hoch - Reinigen - Quelle prüfen",
    "PM2.5 Erhöht - Reiniger erwägen",
    "PM10 Sehr hoch! Reinigen - Quelle prüfen",
    "PM10 Hoch - Reinigen - Staub reduzieren",
    "PM10 Erhöht - Staub reduzieren",
    "HCHO Sehr hoch! Lüften - Quelle weg",
    "HCHO Hoch - Lüften - Quelle weg",
    "HCHO Erkannt - Quellen prüfen",
    "VOC Sehr hoch! Quelle finden - lüften",
    "VOC Hoch - Mehr lüften",
    "NOx Sehr hoch! Quelle stoppen - lüften",
    "NOx Hoch - Abzug nutzen - Quelle prüfen",
    "NOx Erhöht - Herd/Außen prüfen",
    "Zu kalt! Heizen",
    "Kalt - Raum heizen",
    "Etwas kühl - Mehr Wärme",
    "Zu heiß! Kühlen",
    "Warm - Lüften / kühlen",
    "Etwas warm - Mehr Luft",
    "DP Sehr niedrig! Befeuchten",
    "DP Niedrig - Luft kann trocken sein",
    "DP Schwül! Entfeuchten",
    "DP Sehr hoch - Lüften/entfeuchten",
    "DP Hoch - Luft kann schwül sein",
    "Luftfeuchte Extrem niedrig! Befeuchten",
    "Luftfeuchte Sehr niedrig - Befeuchter",
    "Luftfeuchte Niedrig - Befeuchter erwägen",
    "Luftfeuchte Extrem hoch! Entfeuchten",
    "Luftfeuchte Sehr hoch - Entfeuchten",
    "Luftfeuchte Hoch - Mehr Luft",
    "EINSTELL",
    "ZURÜCK",
    "TEMP-KORR.",
    "FEUCHT-KORR.",
    "NACHTMODUS",
    "C / F",
    "HEAD STATUS",
    "WI-FI",
    "ZEIT / DATUM",
    "THEME FARBE",
    "MQTT",
    "AUTO NACHT",
    "NEUSTART",
    "WERKS\nRESET",
    "CO2\nKALIBR.",
    "INFO",
    "PUNKT\nANZEIGE",
    "ALARM\nBLINK",
    "VOC\nNEU LERN.",
    "HINTERLICHT",
    "WLAN EINSTELLUNGEN",
    "WLAN Status:",
    "WLAN einrichten:\n- ON / OFF drücken\n- Mit \"ProjectAura-Setup\" verbinden\n- http://192.168.4.1 öffnen oder QR-Code scannen\n- Heimnetz wählen und Passwort eingeben\n",
    "SSID:",
    "IP:",
    "WLAN\nLÖSCHEN",
    "VERBINDEN",
    "AP START",
    "MQTT EINSTELLUNGEN",
    "MQTT Status:",
    "MQTT einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/mqtt öffnen oder QR-Code scannen",
    "Gerät IP:",
    "Broker IP:",
    "Topic:",
    "VERBINDEN",
    "DATUM & ZEIT",
    "ZEITZONE",
    "AUTO SYNC (NTP)",
    "ZEIT SETZEN",
    "Stunden:",
    "Minuten:",
    "DATUM SETZEN",
    "Tag:",
    "Monat:",
    "Jahr:",
    "ZEIT",
    "JETZT ANWENDEN",
    "RTC:",
    "WLAN:",
    "NTP:",
    "STATUS: ",
    "TEMPERATUR",
    "LUFTFEUCHTE",
    "DRUCK",
    "WARMLAUF",
    "VOC RESET",
    "NEUSTART",
    "RESET",
    "ABBRECHEN",
    "VOC-Kalibrierung zurücksetzen?",
    "VOC/NOx-Lernen wird neu gestartet.\nWerte können einige Stunden instabil sein.",
    "Gerät neu starten?",
    "Das Gerät wird neu gestartet.\nMesswerte pausieren kurz.",
    "Werkseinstellungen zurücksetzen?",
    "Dies löscht WLAN, Offsets, Themes,\nZeitpläne und VOC-Status.\nDies kann nicht rückgängig gemacht werden.",
    "THEME:",
    "EIGEN",
    "VORLAGEN",
    "BEISPIEL:",
    "Custom-Theme einrichten:\n- Project Aura zuerst mit WLAN verbinden\n- http://aura.local/theme öffnen oder QR-Code scannen\n- Mit Zurück speichern",
    "AUTO NACHTMODUS",
    "Diese Funktion aktiviert \"Nachtmodus\" nach Zeitplan.\n- Start- und Endzeit einstellen.\n- Schalter auf AN.\n- Manueller Nachtmodus ist deaktiviert,\n  wenn Auto Nacht aktiv ist.",
    "STARTZEIT",
    "ENDZEIT",
    "HINTERLICHT",
    "Gerät überwacht Luftqualität bei ausgeschaltetem Bildschirm.\nSensoren bleiben aktiv. Berühren zum Aufwecken.",
    "GEPLANTER SCHLAF",
    "ENERGIESPAREN",
    "SCHLAFEN UM",
    "AUFWACHEN UM",
    "IMMER AN",
    "30 SEK",
    "1 MIN",
    "5 MIN",
    "CO2 Kalibrierung (Frischluft)",
    "CO2 KALIBRIEREN",
    "- ASC (Auto-Selbstkalibrierung): Standardmäßig AN.\n- Am besten, wenn CO2 mind. wöchentlich nahe Außenluft fällt\n  (gute Lüftung / Raum unbesetzt).\n- ASC passt sich langsam über Tage an (nicht sofort).\n- Mit ASC AN ist manuelle Kalibrierung meist nicht nötig.",
    "- Gerät mit Powerbank betreiben.\n- Nach draußen an frische Luft bringen.\n- Fern von Menschen (Atem), Fenstern, Autos, Rauch, Lüftungen.\n- 10 Minuten laufen lassen (mind. 5).\n- CO2 kalibrieren drücken und Gerät ruhig halten.\n- Manuelle Kalibrierung nur zur Fehlersuche.\n- Nicht öfter als alle 6 Monate kalibrieren.\n- Kalibrierung nutzt 420 ppm Referenz.\n- Falsche Bedingungen verschlechtern die Messung.",
    "TIPPE ZUM FORTFAHREN",
    "BOOT-DIAGNOSE",
    "System",
    "Sensoren",
    "App:",
    "MAC:",
    "Reset:",
    "Heap:",
    "Speicher:",
    "I2C:",
    "Touch:",
    "SEN66:",
    "SFA30:",
    "RTC:",
    "Fehler erkannt",
    "OK (Konfig)",
    "OK (Standard)",
    "WIEDER OK",
    "ERKANNT",
    "FEHLER",
    "STARTET...",
    "NICHT GEFUNDEN",
    "VERLOREN"
};

static_assert(sizeof(kStringsDe) / sizeof(kStringsDe[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: DE table size mismatch");

// TODO: fill translations. Null entries fall back to English.
constexpr const char *kStringsEs[static_cast<size_t>(TextId::Count)] = {};

static_assert(sizeof(kStringsEn) / sizeof(kStringsEn[0]) ==
              static_cast<size_t>(TextId::Count),
              "UiStrings: EN table size mismatch");

Language g_language = Language::EN;

const char *const *tableFor(Language lang) {
    switch (lang) {
        case Language::DE: return kStringsDe;
        case Language::ES: return kStringsEs;
        case Language::EN:
        default:
            return kStringsEn;
    }
}

} // namespace

void setLanguage(Language lang) {
    g_language = lang;
}

Language language() {
    return g_language;
}

const char *text(TextId id) {
    const size_t index = static_cast<size_t>(id);
    const char *const *table = tableFor(g_language);
    const char *value = table ? table[index] : nullptr;
    if (!value || !*value) {
        value = kStringsEn[index];
    }
    return value ? value : "";
}

} // namespace UiStrings
