idf_component_get_property(aura_arduino_dir espressif__arduino-esp32 COMPONENT_DIR)
set(aura_sta_source "${aura_arduino_dir}/libraries/WiFi/src/STA.cpp")
set(aura_sta_overlay "${CMAKE_BINARY_DIR}/generated/arduino-wifi/STA.cpp")
execute_process(COMMAND "${Python3_EXECUTABLE}" "${CMAKE_SOURCE_DIR}/scripts/idf_arduino_wifi_overlay.py"
    --source "${aura_sta_source}" --destination "${aura_sta_overlay}"
    COMMAND_ERROR_IS_FATAL ANY)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
    "${CMAKE_SOURCE_DIR}/scripts/idf_arduino_wifi_overlay.py" "${aura_sta_source}")
get_target_property(aura_arduino_sources __idf_espressif__arduino-esp32 SOURCES)
set(aura_arduino_patched_sources)
set(aura_sta_replaced 0)
foreach(aura_source IN LISTS aura_arduino_sources)
    if(aura_source MATCHES "(^|/)libraries/WiFi/src/STA[.]cpp$")
        list(APPEND aura_arduino_patched_sources "${aura_sta_overlay}")
        math(EXPR aura_sta_replaced "${aura_sta_replaced} + 1")
    else()
        list(APPEND aura_arduino_patched_sources "${aura_source}")
    endif()
endforeach()
if(NOT aura_sta_replaced EQUAL 1)
    message(FATAL_ERROR "Expected exactly one Arduino STA source, found ${aura_sta_replaced}")
endif()
set_property(TARGET __idf_espressif__arduino-esp32 PROPERTY SOURCES "${aura_arduino_patched_sources}")
target_include_directories(__idf_espressif__arduino-esp32 PRIVATE "${aura_arduino_dir}/libraries/WiFi/src")
