#pragma once

// Native-IDF build only. Both Aura profiles use ST7262, GT911, CH422G and
// the project custom backlight callback from esp_panel_board_custom_conf.h.
// Do not compile drivers for unrelated boards while migrating these profiles.
#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_MAJOR 1
#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_MINOR 2
#define ESP_PANEL_DRIVERS_CONF_FILE_VERSION_PATCH 0

#define ESP_PANEL_DRIVERS_BUS_USE_ALL 0
#define ESP_PANEL_DRIVERS_BUS_USE_RGB 1
#define ESP_PANEL_DRIVERS_BUS_USE_I2C 1
#define ESP_PANEL_DRIVERS_BUS_COMPILE_UNUSED_DRIVERS 0

#define ESP_PANEL_DRIVERS_LCD_USE_ALL 0
#define ESP_PANEL_DRIVERS_LCD_USE_ST7262 1
#define ESP_PANEL_DRIVERS_LCD_COMPILE_UNUSED_DRIVERS 0

#define ESP_PANEL_DRIVERS_TOUCH_USE_ALL 0
#define ESP_PANEL_DRIVERS_TOUCH_USE_GT911 1
#define ESP_PANEL_DRIVERS_TOUCH_COMPILE_UNUSED_DRIVERS 0

#define ESP_PANEL_DRIVERS_EXPANDER_USE_ALL 0
#define ESP_PANEL_DRIVERS_EXPANDER_USE_CH422G 1

#define ESP_PANEL_DRIVERS_BACKLIGHT_USE_ALL 0
#define ESP_PANEL_DRIVERS_BACKLIGHT_USE_CUSTOM 1
#define ESP_PANEL_DRIVERS_BACKLIGHT_COMPILE_UNUSED_DRIVERS 0
