Import("env")

import os
import subprocess


def _run_git(args):
    try:
        return subprocess.check_output(
            ["git"] + args,
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception:
        return ""


def _project_option(name, default=""):
    value = env.GetProjectOption(name, default)
    return str(value).strip()


def resolve_build_id():
    short_sha = _run_git(["rev-parse", "--short=7", "HEAD"])
    if not short_sha:
        return "nogit"

    suffix = _project_option("custom_build_id_suffix")
    build_id = f"{short_sha}-{suffix}" if suffix else short_sha
    # Untracked source/header files can participate in a PlatformIO build just
    # like tracked files. Include them so a physical-test artifact never looks
    # commit-clean when its compiled inputs are not fully represented by HEAD.
    dirty = _run_git(["status", "--porcelain"])
    if dirty:
        return f"{build_id}-dirty"
    return build_id


def _c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_if_changed(path, content):
    try:
        with open(path, "r", encoding="utf-8") as existing:
            if existing.read() == content:
                return
    except FileNotFoundError:
        pass

    with open(path, "w", encoding="utf-8", newline="\n") as generated:
        generated.write(content)


hardware_profile = _project_option("custom_hardware_profile", "unknown") or "unknown"
build_id_suffix = _project_option("custom_build_id_suffix")
profile_config = {
    "4_3": {"is_7_inch": 0, "build_id_suffix": ""},
    "7_dual_i2c_scl6": {
        "is_7_inch": 1,
        "build_id_suffix": "7_dual_i2c_scl6",
    },
}.get(hardware_profile)
if profile_config is None:
    raise RuntimeError(f"Unsupported custom_hardware_profile: {hardware_profile}")
if build_id_suffix != profile_config["build_id_suffix"]:
    raise RuntimeError(
        "custom_build_id_suffix does not match custom_hardware_profile: "
        f"profile={hardware_profile} suffix={build_id_suffix}"
    )

env.AppendUnique(
    CPPDEFINES=[
        ("AURA_HARDWARE_PROFILE_7", profile_config["is_7_inch"]),
    ]
)

generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated_dir, exist_ok=True)

header_path = os.path.join(generated_dir, "AppBuildId.generated.h")
header = (
    "// Generated by scripts/set_build_id.py; do not edit.\n"
    "#pragma once\n\n"
    f"#define APP_BUILD_ID {_c_string(resolve_build_id())}\n"
    f"#define APP_HARDWARE_PROFILE {_c_string(hardware_profile)}\n"
)

_write_if_changed(header_path, header)
env.Append(CPPPATH=[generated_dir])
