Import("env")

import json
import os
import subprocess


def _run_git(args, *, required=False):
    try:
        return subprocess.check_output(
            ["git"] + args,
            cwd=env["PROJECT_DIR"],
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except Exception as error:
        if required:
            command = " ".join(["git"] + args)
            raise RuntimeError(f"Required Git command failed: {command}") from error
        return ""


def _project_option(name, default=""):
    value = env.GetProjectOption(name, default)
    return str(value).strip()


def resolve_build_id():
    short_sha = _run_git(["rev-parse", "--short=7", "HEAD"])
    if not short_sha:
        return "nogit"

    suffix = _project_option("custom_build_id_suffix")
    build_id = f"{short_sha}-{suffix}" if suffix else short_sha
    # Untracked source/header files can participate in a PlatformIO build just
    # like tracked files. Include them so a physical-test artifact never looks
    # commit-clean when its compiled inputs are not fully represented by HEAD.
    dirty = _run_git(["status", "--porcelain"], required=True)
    if dirty:
        return f"{build_id}-dirty"
    return build_id


def _c_string(value):
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _write_if_changed(path, content):
    try:
        with open(path, "r", encoding="utf-8") as existing:
            if existing.read() == content:
                return
    except FileNotFoundError:
        pass

    with open(path, "w", encoding="utf-8", newline="\n") as generated:
        generated.write(content)


hardware_profile = _project_option("custom_hardware_profile", "unknown") or "unknown"
hardware_target = _project_option("custom_hardware_target", "unknown") or "unknown"
build_id_suffix = _project_option("custom_build_id_suffix")
partitions_file = _project_option(
    "board_build.partitions", "partitions_16MB_littlefs.csv"
) or "partitions_16MB_littlefs.csv"
profile_config = {
    "4_3": {
        "is_7_inch": 0,
        "build_id_suffix": "",
        "hardware_target": "aura-aq-v1",
    },
    "7_dual_i2c_scl6": {
        "is_7_inch": 1,
        "build_id_suffix": "7_dual_i2c_scl6",
        "hardware_target": "aura-aq-7-v1",
    },
}.get(hardware_profile)
if profile_config is None:
    raise RuntimeError(f"Unsupported custom_hardware_profile: {hardware_profile}")
if build_id_suffix != profile_config["build_id_suffix"]:
    raise RuntimeError(
        "custom_build_id_suffix does not match custom_hardware_profile: "
        f"profile={hardware_profile} suffix={build_id_suffix}"
    )
if hardware_target != profile_config["hardware_target"]:
    raise RuntimeError(
        "custom_hardware_target does not match custom_hardware_profile: "
        f"profile={hardware_profile} target={hardware_target}"
    )

env.AppendUnique(
    CPPDEFINES=[
        ("AURA_HARDWARE_PROFILE_7", profile_config["is_7_inch"]),
    ]
)

generated_dir = os.path.join(env.subst("$BUILD_DIR"), "generated")
os.makedirs(generated_dir, exist_ok=True)

header_path = os.path.join(generated_dir, "AppBuildId.generated.h")
build_id = resolve_build_id()
source_commit = _run_git(["rev-parse", "HEAD"])
header = (
    "// Generated by scripts/set_build_id.py; do not edit.\n"
    "#pragma once\n\n"
    f"#define APP_BUILD_ID {_c_string(build_id)}\n"
    f"#define APP_HARDWARE_PROFILE {_c_string(hardware_profile)}\n"
    f"#define APP_HARDWARE_TARGET {_c_string(hardware_target)}\n"
)

_write_if_changed(header_path, header)
identity_path = os.path.join(generated_dir, "build-identity.json")
identity = {
    "schema": "project-aura.build-identity.v1",
    "environment": str(env.subst("$PIOENV")),
    "source_commit": source_commit,
    "build_id": build_id,
    "hardware_profile": hardware_profile,
    "hardware_target": hardware_target,
    "partitions_file": partitions_file,
}
_write_if_changed(identity_path, json.dumps(identity, indent=2, sort_keys=True) + "\n")
env.Append(CPPPATH=[generated_dir])
